### ISSUE TITLE
[Bug] Swipe controls not working in portrait/vertical videos

### ISSUE THREAD

**Issue by calvinbui** [YTVanced/Vanced#138]
**Bug description**
Swipe controls do not work on portrait/vertical videos. Instead, the video exits full-screen mode.

**Variant**
NonRoot

**Vanced version**
15.40.37

**Android version**
Android 10

**Device**
Samsung Galaxy 10+

**Steps to Reproduce**
Steps to reproduce the error:
1. Open the app
2. Play a portrait/vertical video
3. Press the full-screen button on the video player to enter full-screen mode
4. Swipe up/down on either left or right side to change volume and brightness
5. Full screen mode is exited

**Expected behavior**
Brightness or volume is increased/decreased

Related: https://github.com/YTVanced/Vanced/issues/51

**Comment by calvinbui** [comment]
Working on 14.21 but still broken on latest versions as of today (16)

**Comment by calvinbui** [comment]
Still not working in 16.02.35

Tested with https://www.youtube.com/watch?v=ZnF4m8PD8Dg

**Comment by calvinbui** [comment]
Still an issue

**Comment by KevinX8** [comment]
Oh damn you're the OG, we only found out ourselves by accident lol

**Comment by Harmonie666** [comment]
Yes, just noticed this aswell. Would be nice if they worked in vertical mode.

**Comment by am2222** [comment]
They work for me with the latest version. But they keep forgettimg the last state everytime minimize video. The screen brighness keeps jumping to under 30% everytime. I tried to clean catch but did not work. I am afraid if I clean the app data my login disappears and I cannot log in again.

**Comment by MinhBu95** [comment]
Still an issue on 16.16.38

**Comment by milindgoel15** [comment]
It has been fixed internally so please wait for future updates. Closing this issue for now.

**Comment by milindgoel15** [comment]
Should be working with v16.20. If not, feel free to report.

**Comment by MinhBu95** [comment]
Hi Vanced Team,

My current version is 16.20.35 and the issue still persists.
I'll attach a video for your reference.
 Screen_Recording_20210805-101002.mp4
<https://drive.google.com/file/d/1D9Dvg_57aqMYarZDwYlHnpTSbIRqJsfp/view?usp=drive_web>

Thank you for fixing this bug for us 😊
[image: Screenshot_20210805-100830_Vanced Manager.png]



*Warm regards,*
*Minh Bui Cong (Mr.)*
*Tel: (+84) 36 201 6991*

* <http://www.linkedin.com/in/congminhbui>*

**Comment by milindgoel15** [comment]
If you want us to look ur issue and help you, u have make ur link open.

**Comment by MinhBu95** [comment]
Hi,
*This is
<https://drive.google.com/file/d/1D9Dvg_57aqMYarZDwYlHnpTSbIRqJsfp/view?usp=sharing>
*the video link.

Apologies for the late response.



*Warm regards,*
*Minh Bui Cong (Mr.)*
*Tel: (+84) 36 201 6991*

* <http://www.linkedin.com/in/congminhbui>*
