### ISSUE TITLE
Crashing after phone reboot

### ISSUE THREAD

**Issue by XorogVEVO** [YTVanced/Vanced#79]
(forgive me for my grammar, im writing this on my phone)

I recently started using the vanced manager to keep youtube vanced up to date. However, whenever i reboot my phone and i try to open the youtube app, it just crashes. It doesnt even show the yt vanced logo but instead the default yt one.

To fix it, i have to uninstall the app through the vanced manager and install it again. Pressing reinstall isnt working.

Im open to provide any information thats needed, i just dont know what to provide now.

Im not exactly sure if this is an issue with yt vanced or the vanced manager. Im just gonna hope this is the right one.

**Comment by FriedOvaries** [comment]
I'm having the same exact issue except I don't have to reboot. The app will just randomly start crashing after half a day, and nothing works until I uninstall/install. I've tried clearing app cache, reinstall, rebooting, etc. 

I have YT Vanced installed with root but also have microG and TY music installed non-root. 
Android 11
Pixel 2XL

**Comment by Oizaro** [comment]
Cause found: https://proandroiddev.com/oreo-notification-feature-a-critical-issue-that-could-restart-your-android-phone-ca122fa4d9cb

Will be fixed tomorrow.

**Comment by Oizaro** [comment]
@FriedOvaries 

Send a logcat.

**Comment by FriedOvaries** [comment]
> @FriedOvaries
> 
> Send a logcat.

Here you go.
[log.txt](https://github.com/YTVanced/Vanced/files/5420064/log.txt)

**Comment by Oizaro** [comment]
@XorogVEVO @FriedOvaries try this:

https://mega.nz/file/0REi1RoT#4huEVKFaYYrhhoazytk4OI4-XgkaTQKtiQAexwZu8X0

**Comment by XorogVEVO** [comment]
It's no problem with microg. Atleast for me. I'm using the rooted version of YouTube Vanced. I don't have MicroG installed either.

Anyways.. My issue seems to have been fixed by either a Vanced Manager Update or YouTube Vanced Update. (Both happenend in the last 12 days). I'll keep this issue open for @FriedOvaries tho.

**Comment by FriedOvaries** [comment]
Yeah this issue is definitely still occuring for me. YT Vanced starting crashing again this morning after power cycling my phone.

**Comment by FriedOvaries** [comment]
I just upgraded to 15.43.32. I am still experiencing the Vanced app going missing after reboot and crashing on the new update. 

Looks like #81 is the exact same issue.

**Comment by EL-S** [comment]
I'm still having this problem on 15.43.32

**Comment by Behike** [comment]
Hey there !
As this issue is still opened, here are some logs so someone can eventually find a patch. I did three different logs, one at phone start (without doing anything), one when opening the app after a restart (when the app crashes) and another during Youtube Vanced reinstallation (uninstall/update using Vanced Manager).
[log after phone restart.txt](https://github.com/YTVanced/Vanced/files/5535355/log.after.phone.restart.txt)
[log open after restart 2.txt](https://github.com/YTVanced/Vanced/files/5535356/log.open.after.restart.2.txt)
[log open after restart.txt](https://github.com/YTVanced/Vanced/files/5535357/log.open.after.restart.txt)

**Comment by milindgoel15** [comment]
Please update to the latest vanced manager release if you haven't already. Refer to issue #123 
If you still have any issue, feel free to reopen.
